### ISSUE TITLE
Теперь код понятен?

### ISSUE THREAD

**Issue by nm17** [IngenerkaTeamNewYork/PreLevelMap#1]
Думаю что все более менее нормально.
Ничего сложного не наблюдаю в коде.

**Comment by mabramovsd** [comment]
Достаточно понятный (староверам, не признающим существование библиотек кроме TXLib.h, за 5-10 минут объяснить можно)
P.S. Думаю, имеет смысл cfg.json тоже скинуть в репозиторий

**Comment by nm17** [comment]
@mabramovsd cfg.json добавлен. cc4481d
